-- 2nd, tidy the JSON so we can explode it easily
-- This means 
-- (i) Extracting the `entries` array
-- (ii) For each entry in that array, picking out the `key` and making it a primary key in the resulting JSON
-- (iii) For each entry in that array, picking out the `value` and making it the value in the resulting JSON
-- Note that we end up building 3 JSONs rather than one because the json_build_object function only seems to support 50 key/value pairs
drop materialized view if exists scratch.admissions_form_tidy_json;
create materialized view scratch.admissions_form_tidy_json as (
    select
    uid,
    ingested_at,
    json_build_object(
		coalesce(	"data"->'entries'->	0	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	0	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	1	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	1	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	2	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	2	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	3	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	3	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	4	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	4	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	5	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	5	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	6	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	6	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	7	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	7	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	8	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	8	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	9	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	9	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	10	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	10	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	11	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	11	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	12	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	12	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	13	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	13	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	14	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	14	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	15	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	15	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	16	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	16	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	17	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	17	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	18	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	18	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	19	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	19	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	20	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	20	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	21	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	21	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	22	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	22	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	23	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	23	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	24	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	24	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	25	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	25	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	26	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	26	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	27	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	27	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	28	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	28	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	29	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	29	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	30	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	30	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	31	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	31	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	32	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	32	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	33	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	33	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	34	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	34	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	35	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	35	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	36	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	36	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	37	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	37	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	38	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	38	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	39	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	39	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	40	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	40	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	41	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	41	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	42	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	42	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	43	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	43	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	44	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	44	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	45	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	45	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	46	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	46	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	47	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	47	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	48	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	48	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	49	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	49	->'values'->0->>'value',	'blank')
    ) as first_tidy_json,

    json_build_object(
		coalesce(	"data"->'entries'->	50	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	50	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	51	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	51	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	52	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	52	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	53	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	53	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	54	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	54	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	55	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	55	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	56	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	56	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	57	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	57	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	58	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	58	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	59	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	59	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	60	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	60	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	61	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	61	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	62	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	62	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	63	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	63	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	64	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	64	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	65	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	65	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	66	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	66	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	67	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	67	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	68	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	68	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	69	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	69	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	70	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	70	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	71	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	71	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	72	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	72	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	73	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	73	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	74	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	74	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	75	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	75	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	76	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	76	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	77	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	77	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	78	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	78	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	79	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	79	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	80	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	80	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	81	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	81	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	82	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	82	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	83	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	83	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	84	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	84	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	85	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	85	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	86	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	86	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	87	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	87	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	88	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	88	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	89	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	89	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	90	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	90	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	91	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	91	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	92	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	92	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	93	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	93	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	94	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	94	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	95	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	95	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	96	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	96	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	97	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	97	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	98	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	98	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	99	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	99	->'values'->0->>'value',	'blank')
    ) as second_tidy_json,

    json_build_object(
		coalesce(	"data"->'entries'->	100	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	100	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	101	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	101	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	102	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	102	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	103	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	103	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	104	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	104	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	105	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	105	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	106	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	106	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	107	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	107	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	108	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	108	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	109	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	109	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	110	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	110	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	111	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	111	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	112	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	112	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	113	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	113	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	114	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	114	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	115	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	115	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	116	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	116	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	117	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	117	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	118	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	118	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	119	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	119	->'values'->0->>'value',	'blank'),
		coalesce(	"data"->'entries'->	120	->>'key',	'blank'), 	coalesce(	"data"->'entries'->	120	->'values'->0->>'value',	'blank')
    ) as third_tidy_json
    from scratch.deduplicated_admissions
);
