drop materialized view if exists scratch.discharges_form_exploded;
create materialized view scratch.discharges_form_exploded as
select
    uid,
    ingested_at,

	first_tidy_json->>	'Apgar10DC'	 as 	"Apgar10DC",
	first_tidy_json->>	'Apgar1DC'	 as 	"Apgar1DC",
	first_tidy_json->>	'Apgar5DC'	 as 	"Apgar5DC",
	first_tidy_json->>	'blank'	 as 	"blank",
	first_tidy_json->>	'BWDC'	 as 	"BWDC",
	first_tidy_json->>	'CadreDis'	 as 	"CadreDis",
	first_tidy_json->>	'CauseDeath'	 as 	"CauseDeath",
	first_tidy_json->>	'CauseDeathOther'	 as 	"CauseDeathOther",
	first_tidy_json->>	'CLINREVDAT'	 as 	"CLINREVDAT",
	first_tidy_json->>	'ContCauseDeath'	 as 	"ContCauseDeath",
	first_tidy_json->>	'ContribOth'	 as 	"ContribOth",
	first_tidy_json->>	'DateAdmissionDC'	 as 	"DateAdmissionDC",
	first_tidy_json->>	'DateDischVitals'	 as 	"DateDischVitals",
	first_tidy_json->>	'DateDischWeight'	 as 	"DateDischWeight",
	first_tidy_json->>	'DateTimeDeath'	 as 	"DateTimeDeath",
	first_tidy_json->>	'DateTimeDischarge'	 as 	"DateTimeDischarge",
	first_tidy_json->>	'DateWeaned'	 as 	"DateWeaned",
	first_tidy_json->>	'DIAGDIS1'	 as 	"DIAGDIS1",
	first_tidy_json->>	'DIAGDIS1OTH'	 as 	"DIAGDIS1OTH",
	first_tidy_json->>	'DischHR'	 as 	"DischHR",
	first_tidy_json->>	'DischRR'	 as 	"DischRR",
	first_tidy_json->>	'DischSats'	 as 	"DischSats",
	first_tidy_json->>	'DischTemp'	 as 	"DischTemp",
	first_tidy_json->>	'DischWeight'	 as 	"DischWeight",
	first_tidy_json->>	'EndScriptDatetime'	 as 	"EndScriptDatetime",
	first_tidy_json->>	'FeedsAdm'	 as 	"FeedsAdm",
	first_tidy_json->>	'GestationDC'	 as 	"GestationDC",
	first_tidy_json->>	'HCWIDDis'	 as 	"HCWIDDis",
	first_tidy_json->>	'HCWSigDis'	 as 	"HCWSigDis",
	first_tidy_json->>	'HealthEd'	 as 	"HealthEd",
	first_tidy_json->>	'HIVtestResultDC'	 as 	"HIVtestResultDC",
	first_tidy_json->>	'MEDOTH'	 as 	"MEDOTH",
	first_tidy_json->>	'MedsGiven'	 as 	"MedsGiven",
	first_tidy_json->>	'ModeDeliveryDC'	 as 	"ModeDeliveryDC",
	first_tidy_json->>	'ModFactor1'	 as 	"ModFactor1",
	first_tidy_json->>	'ModFactor2'	 as 	"ModFactor2",
	first_tidy_json->>	'ModFactor3'	 as 	"ModFactor3",
	first_tidy_json->>	'NeoTreeID'	 as 	"NeoTreeID",
	first_tidy_json->>	'NeoTreeOutcome'	 as 	"NeoTreeOutcome",
	first_tidy_json->>	'NUID_S'	 as 	"NUID_S",
	first_tidy_json->>	'OtherProbs'	 as 	"OtherProbs",
	first_tidy_json->>	'OtherProbsOth'	 as 	"OtherProbsOth",
	first_tidy_json->>	'PHOTOTHERAPY'	 as 	"PHOTOTHERAPY",
	first_tidy_json->>	'RESPSUP'	 as 	"RESPSUP",
	first_tidy_json->>	'REVCLIN'	 as 	"REVCLIN",
	first_tidy_json->>	'REVCLINOTH'	 as 	"REVCLINOTH",
	first_tidy_json->>	'REVCLINTYP'	 as 	"REVCLINTYP",
	first_tidy_json->>	'ThermCare'	 as 	"ThermCare",
	first_tidy_json->>	'UIDDC'	 as 	"UIDDC"

from scratch.discharges_form_tidy_json;